version: '3'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <<SETTING_SITE_PASSWORD>>
      MYSQL_DATABASE: <<SETTING_SITE_DATABASENAME>>
      MYSQL_USER: <<SETTING_SITE_ROOTUSER>>
      MYSQL_PASSWORD: <<SETTING_SITE_ROOTUSERPASS>>
    restart: always

  web:
    build: .
    command: sh -c "sleep 3; python3.6 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/root/shiroperu
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  data:
    driver: local
